name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./report/pom.xml
          mvn clean package -f ./location/pom.xml
          mvn clean package -f ./phone/pom.xml
          mvn clean package -f ./cancellog/pom.xml
          mvn clean package -f ./email/pom.xml

      - name: Docker Build and push for Report
        uses: docker/build-push-action@v4
        with:
          context: ./report
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/report:latest
            ghcr.io/${{ github.repository }}/report:${{ github.ref_name }}
            
      - name: Docker Build and push for Location
        uses: docker/build-push-action@v4
        with:
          context: ./location
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/location:latest
            ghcr.io/${{ github.repository }}/location:${{ github.ref_name }}
            
      - name: Docker Build and push for Phone
        uses: docker/build-push-action@v4
        with:
          context: ./phone
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/phone:latest
            ghcr.io/${{ github.repository }}/phone:${{ github.ref_name }}
            
      - name: Docker Build and push for Cancellog
        uses: docker/build-push-action@v4
        with:
          context: ./cancellog
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/cancellog:latest
            ghcr.io/${{ github.repository }}/cancellog:${{ github.ref_name }}
            
      - name: Docker Build and push for Email
        uses: docker/build-push-action@v4
        with:
          context: ./email
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/email:latest
            ghcr.io/${{ github.repository }}/email:${{ github.ref_name }}
            
